export const Skill_set = [
  {
    skill_name: 'Html 5',
    Image: '/html.png',
    width: 60,
    height: 60,
  },
  {
    skill_name: 'CSS',
    Image: '/css.png',
    width: 66,
    height: 66,
  },
  {
    skill_name: 'Java Script',
    Image: '/js.png',
    width: 48,
    height: 48,
    style: 5,
  },
  {
    skill_name: 'Tailwind Css',
    Image: '/tailwind.png',
    width: 65,
    height: 65,
  },
  {
    skill_name: 'Material UI',
    Image: '/mui.png',
    width: 65,
    height: 65,
  },
  {
    skill_name: 'React',
    Image: '/react.png',
    width: 65,
    height: 65,
    style: 4,
  },
  {
    skill_name: 'Redux Toolkit',
    Image: '/redux.png',
    width: 55,
    height: 55,
    style: '',
  },
  {
    skill_name: 'Type Script',
    Image: '/ts.png',
    width: 50,
    height: 50,
  },
  {
    skill_name: 'Next js 14',
    Image: '/next.png',
    width: 55,
    height: 55,
  },
  {
    skill_name: 'Framer Motion',
    Image: '/framer.png',
    width: 50,
    height: 50,
  },
  {
    skill_name: 'Stripe',
    Image: '/stripe.webp',
    width: 50,
    height: 50,
  },
  {
    skill_name: 'Node js',
    Image: '/node-js.png',
    width: 50,
    height: 50,
  },
  {
    skill_name: 'Express js',
    Image: '/express.png',
    width: 50,
    height: 50,
  },
  {
    skill_name: 'Mongo db',
    Image: '/mongodb.png',
    width: 30,
    height: 30,
  },
  {
    skill_name: 'Docker',
    Image: '/docker.webp',
    width: 60,
    height: 60,
    style: 6,
  },

  {
    skill_name: 'Figma',
    Image: '/figma.png',
    width: 35,
    height: 35,
    style: 4,
  },
]
