export const Skill_set = [
  {
    skill_name: 'Html 5',
    Image: '/html.webp',
    width: 60,
    height: 60,
  },
  {
    skill_name: 'CSS',
    Image: '/css.webp',
    width: 66,
    height: 66,
  },
  {
    skill_name: 'Java Script',
    Image: '/js.webp',
    width: 48,
    height: 48,
    style: 5,
  },
  {
    skill_name: 'Tailwind Css',
    Image: '/tailwind.webp',
    width: 65,
    height: 65,
  },
  {
    skill_name: 'Material UI',
    Image: '/mui.webp',
    width: 57,
    height: 57,
    style: 5,
  },
  {
    skill_name: 'React',
    Image: '/react.webp',
    width: 55,
    height: 50,
    style: 4,
  },
  {
    skill_name: 'React Query',
    Image: '/reactquery.webp',
    width: 60,
    height: 60,
    style: 4,
  },
  {
    skill_name: 'Redux Toolkit',
    Image: '/redux.webp',
    width: 50,
    height: 50,
    style: 5,
  },
  {
    skill_name: 'Type Script',
    Image: '/ts.webp',
    width: 50,
    height: 50,
  },
  {
    skill_name: 'Next js 14',
    Image: '/next.webp',
    width: 55,
    height: 55,
  },
  {
    skill_name: 'Framer Motion',
    Image: '/framer.webp',
    width: 50,
    height: 50,
  },
  {
    skill_name: 'Stripe',
    Image: '/stripe.webp',
    width: 50,
    height: 50,
  },
  {
    skill_name: 'Node js',
    Image: '/node-js.webp',
    width: 57,
    height: 57,
  },
  {
    skill_name: 'Express js',
    Image: '/express.webp',
    width: 50,
    height: 50,
  },
  {
    skill_name: 'Mongo db',
    Image: '/mongodb.webp',
    width: 56,
    height: 56,
  },
  {
    skill_name: 'Docker',
    Image: '/docker.webp',
    width: 60,
    height: 60,
    style: 6,
  },

  {
    skill_name: 'Figma',
    Image: '/figma.webp',
    width: 35,
    height: 35,
    style: 4,
  },
]
