export const Skill_set = [
  {
    skill_name: 'Html5',
    Image: '/html.webp',
    width: 40,
    height: 40,
  },
  {
    skill_name: 'CSS',
    Image: '/css.webp',
    width: 45,
    height: 45,
  },
  {
    skill_name: 'Java Script',
    Image: '/js.webp',
    width: 32,
    height: 32,
    style: 3,
  },
  {
    skill_name: 'Tailwind Css',
    Image: '/tailwind.webp',
    width: 45,
    height: 45,
  },
  {
    skill_name: 'Material UI',
    Image: '/mui.webp',
    width: 47,
    height: 47,
  },
  {
    skill_name: 'React',
    Image: '/react.webp',
    width: 36,
    height: 36,
    style: 4,
  },
  {
    skill_name: 'React Query',
    Image: '/reactquery.webp',
    width: 40,
    height: 40,
  },
  {
    skill_name: `ReduxToolkit`,
    Image: '/redux.webp',
    width: 35,
    height: 35,
  },
  {
    skill_name: 'Type Script',
    Image: '/ts.webp',
    width: 30,
    height: 30,
  },
  {
    skill_name: 'Next js 14',
    Image: '/next.webp',
    width: 30,
    height: 30,
  },
  {
    skill_name: 'FramerMotion',
    Image: '/framer.webp',
    width: 30,
    height: 30,
  },
  {
    skill_name: 'Stripe',
    Image: '/stripe.webp',
    width: 30,
    height: 30,
  },
  {
    skill_name: 'Node js',
    Image: '/node-js.webp',
    width: 40,
    height: 40,
  },
  {
    skill_name: 'Express js',
    Image: '/express.webp',
    width: 40,
    height: 40,
  },
  {
    skill_name: 'Mongo db',
    Image: '/mongodb.webp',
    width: 45,
    height: 45,
  },
  {
    skill_name: 'Docker',
    Image: '/docker.webp',
    width: 40,
    height: 40,
  },

  {
    skill_name: 'Figma',
    Image: '/figma.webp',
    width: 35,
    height: 35,
  },
]
